project:
  type: website
  output-dir: docs

website:
  title: "PLAN372"
  sidebar:
    search: true
    contents:
      - href: index.qmd
        text: Home
      - first_tutorial.qmd
      - basic_data_wrangling.qmd
      - data_wrangling_continued.qmd
      - exploratory_analysis.qmd
      - fundamental_data_viz.qmd
      - data_viz_continued.qmd
      
format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    toc: true



